### PR TITLE
Remove sort options bar and update display settings

### LINKED ISSUE #2769: Move Sorting Options to Settings
Based on low usage, let's remove the sort bar from both the search results and notes list.

Sorting should now appear in settings in full:

Name: A-Z
Name: Z-A
Created: Newest
Created: Oldest
Modified: Newest
Modified: Oldest

### PR DESCRIPTION
**Pull request by sandymcfadden**
### Fix

Fixes #2769 

This removes the sort options bar from the note list and updates the sort options in the Display Settings to match the options which the sort bar offered. 

**Screenshots**

<details>
<summary>Before</summary>
Screen Shot 2021-04-13 at 8 40 34 AM
Screen Shot 2021-04-13 at 8 41 07 AM
</details>
<details>
<summary>After</summary>
Screen Shot 2021-04-13 at 8 41 47 AM
Screen Shot 2021-04-13 at 8 42 14 AM
</details>

### Test

1. Ensure sort options do not show in the note list.
2. Go to display settings.
3. Ensure the sort options show completely.
4. Ensure the sort options sort appropriately.

### Release

- Removed the sort options bar from the note list and updated the sort options in the Settings.

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Thanks @sandymcfadden 

Looks good! Can we just change "Alphabetically" to "Name" so that the first two sorting options are "Name: A-Z" and "Name Z-A".

**Comment by sandymcfadden** [comment]
Thanks @SylvesterWilmott 

> Looks good! Can we just change "Alphabetically" to "Name" so that the first two sorting options are "Name: A-Z" and "Name Z-A".

I have that updated now.

**Review by SylvesterWilmott — APPROVED** [review]
Thanks @sandymcfadden

**Review by codebykat — APPROVED** [review]
This works as expected. The code looks fine. RIP this component that I personally liked and worked hard on. You were a good component, sort order selector. I'm sorry your time with us was so short.

**Pull request merged**
