### PR TITLE
Replace config.js with config.json in .gitignore

### PR DESCRIPTION
**Pull request by Copons**
The config file was changed from JS to JSON in https://github.com/Automattic/simplenote-electron/pull/477.
This PR prevents accidentally committing it to git.

### CODE REVIEW

**Comment by dmsnell** [comment]
Good call @Copons! can we leave them both in though? it's actually still valid to have a `config.js` as long as it's default export is an object.

**Comment by Copons** [comment]
@dmsnell Dang! I recalled you saying it worked as JS too, but I missed the object part and my tests were failing and I thought it eventually got ditched. Updating this asap.

**Comment by beaucollins** [comment]
To be completely future proof we could do `config.*`.

For instance exporting a plain object in a `config.jsx` file would also work with the [current webpack config](https://github.com/Automattic/simplenote-electron/blob/cac38b16ebec3d066739b1362f4472dada1b5513/webpack.config.js#L29).

**Comment by Copons** [comment]
Three commits to replace `js` with `*`. This might be my best ever!  😆

**Comment by beaucollins** [comment]
@Copons definitely don't squash this one when you merge it 😉.

**Comment by Copons** [comment]
@beaucollins and risking to lose a clean history? No way!

**Pull request merged**
