### PR TITLE
Bump version to 2.1.0-beta2

### PR DESCRIPTION
**Pull request by mokagio**

### CODE REVIEW

**Comment by mokagio** [comment]
I must have forgotten to mark this "Ready for review" after CI returned ✅

**Comment by mokagio** [comment]
I must have forgotten to mark this "Ready for review" after CI returned ✅

**Comment by dmsnell** [comment]
@mokagio are we intending to merge the `2.1.0-beta1` version number into `develop`? I would assume we'd not want to do this until the release is ready and we merge `2.1.0` itself, otherwise isn't this a full release anyways?

**Comment by mokagio** [comment]
It was my intent to merge the beta bump into `develop`. That's what we do with the other apps in the mobile division. The decision predates me, but I assume the rationale is to "communicate" in develop that a beta version has been shipped. There are also technical requirements, such as the GlotPress automation running via `cron` on `develop`.

To me, a beta release is still a release, so it makes sense to merge it, even if it's incomplete. In particular, because we publish them on GitHub as pre-releases, too.

An example that comes to mind of a project that does this is [Bundler](https://bundler.io/). On their main branch, they currently [have version 2.2.0-rc.2](https://github.com/rubygems/rubygems/blob/32f81abc84873c4f4761dfd9dcbd1804a4f6603b/bundler/lib/bundler/version.rb).

**Review by belcherj — APPROVED** [review]

**Pull request merged**
