### PR TITLE
Merge release 2.4.0

### PR DESCRIPTION
**Pull request by mokagio**

### CODE REVIEW

**Comment by mokagio** [comment]
🙄 I tried to merge this locally before opening the PR, but didn't realize I hadn't pulled `develop`...

**Comment by codebykat** [comment]
I don't get it, it's showing changes to `note-utils` (#2529) that were definitely merged in #2524 already.

**Comment by mokagio** [comment]
@codebykat for some reason, I didn't followup this PR with the work I did to fix the merge conflicts, which I the source of the confusion here.

Two things are at play:

- **The _Git history_ shows commits that are already merged**. I'm pretty sure that's because of the "Squash and merge" strategy, which squashes all the commits of a PR into a single one in the base branch.
- **The _diff_ shows changes that should already have been merged**. I'm pretty sure that's again due to the "Squash and merge" plus the fact I didn't resolve the conflicts.

#2558 addresses all these issues.

**Comment by mokagio** [comment]
Closed in favor of #2558 .

**Pull request closed without merging**
