### PR TITLE
#599 Added modification date to note list

### PR DESCRIPTION
**Pull request by natanielcz**

### CODE REVIEW

**Comment by roundhill** [comment]
Thanks for the PR @natanielcz! This is one of those "If we add it here, we should add it to the rest of the apps" things. We do get requests to show the date from users every now and again, so might be worth revisiting. Marking for design review.

**Comment by rodrigoi** [comment]
@drw158 would you mind taking a look at this PR?

**Comment by drw158** [comment]
@natanielcz Can you please add a before and after screenshot of the changes you made? Thanks!

**Comment by natanielcz** [comment]
I'll take care of that after 8th of December.

**Comment by natanielcz** [comment]
## Before changes
### Comfy
screenshot from 2018-01-20 12-47-48
### Condensed
screenshot from 2018-01-20 12-48-36
### Expanded
screenshot from 2018-01-20 12-48-53
## After changes
### Comfy
screenshot from 2018-01-20 12-50-17
### Condensed
screenshot from 2018-01-20 12-50-34
### Expanded
screenshot from 2018-01-20 12-50-49

**Comment by dmsnell** [comment]
1. Would we want the date on all views or limit it to comfy and expanded, or just expanded?

2. Further, would we want to take the same kind of idea present in the WordPress.com notifications to split notes into time groupings with headers for each grouping like, "Today", "Yesterday", "Older than two days", "Older than a week" where we could provide more or less in the date string based on the context of the group?

3. Do we need to display `Modified` or is it clear enough as the chosen sort value?

Thanks for the screenshots @natanielcz!

**Comment by natanielcz** [comment]
1. I thought about that and I think that expanded view is too high right now. So I think that point 2 can help to reduce used space in each view type. If we decide to group them like in Wordpress.com notifications we could avoid the `Modified` text.

**Comment by drw158** [comment]
Sorry for the late response. A few things to think about:

- The sorting options might complicate the idea of using time headers to group notes (last modified, last created, alphabetical, reverse).
- We've never had the date in the note list (if we have it's been a very long time), so this is a pretty big change we should think about across platforms if we proceed.
- The date as it is right now is way too long. It should be something no more than 5 or so characters, like `12:38 AM`, `Jan 12`, or `8/12/17`.

**Comment by natanielcz** [comment]
Maybe we should display modification date as a group title when sorting by modification date is active.
For other sorting types, we could display colored bar on the right 
- green, when a note was modified in last 3 days
- orange, when a note was modified in last 7 days
- red otherwise 

screenshot from 2018-02-26 19-52-03

On hover, we could expand this bar to the right and show modification date more precisely

**Comment by drw158** [comment]
I love the idea of adding the modification date when the date sorting is active!

**Comment by roundhill** [comment]
Closing due to inactivity.

**Pull request closed without merging**
