### PR TITLE
Update display of logo for Windows start menu tile

### LINKED ISSUE #2935: Better tile logo for Microsoft Store version
I need a better start menu tile logo for the Microsoft Store version.
image

### PR DESCRIPTION
**Pull request by sandymcfadden**
### Fix

Fixes #2935

Currently, if you install the appx or Windows store version of Simplenote and then pin it to the start menu the tile generated has a large logo and doesn't show the app name at all. This is different from most other apps installed.

This shrinks the size of the logo and displays the name on the tile. 

Before:
Screen Shot 2021-06-24 at 10 32 48 AM

After:
Screen Shot 2021-06-24 at 10 31 54 AM

### Test

1. Install the appx version of SImplenote
2. Pin the app to the start menu
3. Ensure things look proper with a smaller icon and the app title

### Release

- Updated the logo used when pinning to the Windows start menu.

### CODE REVIEW

**Review by SylvesterWilmott — APPROVED** [review]
Looks good. Thanks @sandymcfadden.

**Review by codebykat — APPROVED** [review]
I'll be honest... I didn't test this. The code changes look straightforward enough and from your screenshots, it solves the problem.

**Comment by xmha97** [comment]
@codebykat Redesign the icon:
Startmenu
The icon is a bit large and also has no shadows.
Please follow the instructions in Microsoft.

**Comment by codebykat** [comment]
Hi @xmha97, I don't actually design (or redesign) anything, I just write code 😅 When you say instructions, is there a standards document somewhere provided by Microsoft that we can follow?

@SylvesterWilmott do you think we should adjust the icon size/shadow? Let's open a new issue to track that if so.

**Comment by xmha97** [comment]
> 
> 
> Hi @xmha97, I don't actually design (or redesign) anything, I just write code 😅 When you say instructions, is there a standards document somewhere provided by Microsoft that we can follow?

This article has been published but I am not aware :(
Maybe this can help a little:
https://docs.microsoft.com/en-us/windows/apps/design/style/app-icons-and-logos#customizing-asset-padding

**Comment by SylvesterWilmott** [comment]
Thanks for the feedback @xmha97. I think we can rectify this!

**Pull request merged**
