### PR TITLE
Merge release 2.22.0 and 2.22.1

### PR DESCRIPTION
**Pull request by mokagio**
Currently a draft PR, waiting for https://github.com/Automattic/simplenote-electron/pull/3232 to land in here with the config-fix and possibly other issues to be addressed.

As a process reminder, once everything is ready we'll want to update the version to drop the `-beta<n>` suffix.

### CODE REVIEW

**Comment by codebykat** [comment]
Cool, I merged #3232. We should close #3226 in favor of this one, right?

**Comment by mokagio** [comment]
> We should close #3226 in favor of this one, right?

Correct @codebykat . Done.

At this point, I think that's all we need before releasing? cc @roundhill 

For reference, here are the steps:

- Update `version` in `package.json` and run `npm install --legacy-peer-deps`
- Push and verify CI is green
- Tag: `git tag v2.22.1 && git push origin v2.22.1`
- Wait for CI to create the release draft
- Double check the artifacts
- Publish the release

I can run these in my tomorrow, unless you want to ship urgently and fell like taking over.

_Update:_ In the meantime, I pushed the `v2.22.1-beta1` tag and will try out the Windows and macOS artifacts later.

**Review by codebykat — APPROVED** [review]
Okay, I've been over the code with a fine-toothed comb and this merge PR looks right. And the build is testing okay (I've only tested on the Mac).

I did notice the version in the `package.json` here does not have the beta tag, which I assume is intentional since this PR won't get merged until the release is finalized. (But please merge it at will! Once these changes are back in `trunk` I'll release the web version just so everything is running the same code... though the build script changes don't change anything on web, so it doesn't really matter.)

**Comment by mokagio** [comment]
> I did notice the version in the package.json here does not have the beta tag, which I assume is intentional since this PR won't get merged until the release is finalized.

Correct @codebykat

The 2.22.1 GitHub release has been published and we have data showing Windows users have been updating. Merging.

**Pull request merged**
