### PR TITLE
Merge 2.13.0-beta1 into develop

### PR DESCRIPTION
**Pull request by oguzkocer**

### CODE REVIEW

**Review by mokagio — COMMENTED** [review]
The huge diff on the `package-lock.json` file is likely due to [the new version of npm](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#changes-to-the-lockfile).

On my end, with npm 6.13.4, the only thing that changes in that file for me after bumping the `version` key in `package.json` is the `version` key.

```diff
diff --git a/package-lock.json b/package-lock.json
index cc2395fa..846aec78 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -1,6 +1,6 @@
 {
   "name": "simplenote",
-  "version": "2.12.0",
+  "version": "2.13.0",
   "lockfileVersion": 1,
   "requires": true,
   "dependencies": {
diff --git a/package.json b/package.json
index 2c6ccb42..e5c93fac 100644
--- a/package.json
+++ b/package.json
@@ -6,7 +6,7 @@
     "email": "support@simplenote.com"
   },
   "productName": "Simplenote",
-  "version": "2.12.0",
+  "version": "2.13.0",
   "main": "desktop/index.js",
   "license": "GPL-2.0",
   "homepage": "https://simplenote.com",
```

Looking at the commit locally (because it's too big for GitHub to render) I see this:

```diff
diff --git a/package-lock.json b/package-lock.json
index cc2395fa..d0cba476 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -1,15 +1,26362 @@
 {
   "name": "simplenote",
-  "version": "2.12.0",
-  "lockfileVersion": 1,
+  "version": "2.13.0-beta1",
+  "lockfileVersion": 2,
   "requires": true,
-  "dependencies": {
-    "7zip-bin": {
+  "packages": {
+    "": {
+      "name": "simplenote",
+      "version": "2.13.0-beta1",
+      "license": "GPL-2.0",
+      "dependencies": {
+        "@automattic/color-studio": "2.3.0",
+        "@material-ui/core": "4.11.0",
+        "@sentry/react": "5.20.1",
+        "clipboard": "2.0.6",
+        "cookie": "0.4.1",
+        "core-js": "3.6.5",
+        "date-fns": "2.14.0",
```

The post I linked above says that this is also backwards compatible with npm v6, and in fact when I tried to run `npm install` I got this

```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```

On the other hand, the diff was:

```diff
diff --git a/package-lock.json b/package-lock.json
index d0cba476..b826e174 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -1,26362 +1,15 @@
 {
   "name": "simplenote",
   "version": "2.13.0-beta1",
-  "lockfileVersion": 2,
+  "lockfileVersion": 1,
   "requires": true,
-  "packages": {
-    "": {
-      "name": "simplenote",
-      "version": "2.13.0-beta1",
-      "license": "GPL-2.0",
-      "dependencies": {
-        "@automattic/color-studio": "2.3.0",
-        "@material-ui/core": "4.11.0",
-        "@sentry/react": "5.20.1",
-        "clipboard": "2.0.6",
-        "cookie": "0.4.1",
-        "core-js": "3.6.5",
-        "date-fns": "2.14.0",
-        "electron-fetch": "1.4.0",
-        "electron-progressbar": "1.2.0",
-        "electron-updater": "4.3.1",
-        "electron-window-state": "5.0.3",
-        "file-saver": "2.0.2",
-        "focus-trap-react": "^8.4.2",
-        "focus-visible": "5.1.0",
-        "gridicons": "3.3.1",
-        "highlight.js": "10.1.1",
```

That is, my `npm` v6 reverted all the v7 changes. 

All this long ramble is to say: if we merge this PR, we should all start using `npm` v7 on this repo. _I have no idea if you can force an `npm` version via `nvm` or if there are drawbacks to adopting v7 (IIRC there were some for Gutenberg?)_ This is a team decision so pinging @Automattic/simplenote-web-reviewers for input on this.

**Comment by oguzkocer** [comment]
@mokagio Great catch! During the release management rush, and since I was handling this repository for the first time, I didn't realize that there was a `.nvmrc` file and just ended up running the `npm install` command with my global node version instead. I've tried to fix this in d1795a0e49b76e28cf3445f9ac282dc00872d103 but it still created a bigger changeset than expected which is likely because the base `package-lock.json` file had incompatible changes. In 11c3c49c67b2ed66a78788d5fc0ea072cf31f962, I've first reverted `package-lock.json` to what it is in `develop` and then ran `npm install` and it (correctly) only updated the version value.

**Comment by oguzkocer** [comment]
@mokagio Once you take a look at this, I think we should remove the beta tag and re-tag it with last commit, so it's created with the correct `package-lock.json`, what do you think?

**Review by mokagio — APPROVED** [review]
Thank you for addressing this @oguzkocer. I think reverting to the npm v6 / lockfile v1 was a great call. It's a big change that deserves its isolated PR, and possibly other kind of tooling updates to ensure every contributor of the repo uses it 👍 

> I think we should remove the beta tag and re-tag it with last commit, so it's created with the correct `package-lock.json`, what do you think?

What do you think of bumping to beta2 instead? Just to avoid issue with the Electron updater, which might have already served beta1 to some users.

I don't actually know if there could be issues (maybe @nsakaimbo does) but because the source of true for that process are the GitHub releases, it might be safer to add one rather than modifying an existing one.

In the meantime, I'm approving this because the tagging and releasing is unrelated to the merging of the PR.

**Comment by oguzkocer** [comment]
> What do you think of bumping to beta2 instead? Just to avoid issue with the Electron updater, which might have already served beta1 to some users.

@mokagio I didn't know if they were being served somewhere and if it was just the Github release, I thought it'd be better to correct the mistake. If it's deployed as you said, I agree that it's better to do a `beta2` instead. It doesn't look like we have any steps for a new beta, so I assume we just create a tag and once it succeeds, we update the release note and publish it on Github. Can you confirm that?

**Comment by oguzkocer** [comment]
@mokagio After merging the PR I realized that there is no protection in `release/2.13.0` branch either, that's another thing we should look into adding so we don't accidentally delete it.

**Comment by mokagio** [comment]
@oguzkocer 

> I didn't know if they were being served somewhere and if it was just the Github release, I thought it'd be better to correct the mistake. If it's deployed as you said...

The @codebykat @sandymcfadden or @dmsnell should be able to confirm this, but that seems to be the case for me, e.g. see this Electron config file https://github.com/Automattic/simplenote-electron/blob/a682de65213b38de0ea8796d688934d1d29bc60e/desktop/config-updater.json

> It doesn't look like we have any steps for a new beta, so I assume we just create a tag and once it succeeds, we update the release note and publish it on Github. Can you confirm that?

Confirmed. As well as following up with PR to merge the `package*.json` version change into develop.

> there is no protection in `release/2.13.0` branch either

Right 😞 . It would be great to automate all that. We could really use a JS version of the release toolkit, but it's all a matter of time and ROI. _We'll get there eventually_ 💪

**Comment by sandymcfadden** [comment]
Sorry for the delay on this. I missed this notification.
I see the beta2 was created already and I think that seems like that was the right option because of the updater as @mokagio  mentioned. 
Thank you for taking care of this!

**Pull request merged**
