### PR TITLE
Fix Offline Sync Issue

### LINKED ISSUE #318: Notes created offline not syncing when online again on Ubuntu 16.04
Notes that are created while working offline are not automatically syncronized when laptop is online again. Not even after a restart of the simplenote program. On Ubuntu 16.04. On Android it does re-syncs!
#### Steps to reproduce
1. Go offline
2. Create a note
3.Go online
4. New note not on https://app.simplenote.com/ even after restart of simplenote program

#### What I expected
All notes that I create while offline should be synced when I go online again. My laptop is not always connected. 

#### What happened instead
Note is only synced after I edit it.

#### OS version
Ubuntu 16.04 Gnome 3.20

### PR DESCRIPTION
**Pull request by roundhill**
Update Simperium to 0.2.2 to fix syncing issue after coming back from being offline.

**To test:** 
* Turn off your network connection.
* Create a new note.
* Turn on your network connection.
* Ensure that the note synced to Simplenote on another device.

Fixes #318

### CODE REVIEW

**Comment by roundhill** [comment]
Simperium ref: https://github.com/Simperium/node-simperium/pull/36

**Comment by rodrigoi** [comment]
I'm experiencing a weird behaviour. When I turn the network back on, other devices show: _New Note..._ while the content is synchronizing, and when the note loads the content is duplicated.

img_0403

img_0404

And the electron app only shows the duplicated content on the notes list.

screen shot 2016-06-13 at 12 42 44

Also, notes created this way don't sync when trashed. You have to trash the note on every device it synchronized.

Tested with Simplenote OSX and iOS.

**Comment by roundhill** [comment]
Hmm, I can reproduce using OS X but not on Windows or Linux... still investigating.

**Comment by roundhill** [comment]
@rodrigoi I enlisted the help of master @beaucollins to fix the duplication weirdness you were seeing. New simperium version published and ready for another look!

**Comment by rodrigoi** [comment]
sync issues looking good, but I trashing notes is not synchronized. If I trash an offline note on a device, it doesn't disappear on the desktop app. Or vice versa. 😕

**Comment by roundhill** [comment]
@rodrigoi trashing syncs for me ¯\_(ツ)_/¯

**Comment by rodrigoi** [comment]
This is what I'm doing:

- deleting `node_modules` and `dist` folders.
- `npm install`
- `make build`
- `electron .` with version `0.36.11`
- disconnect network, create node, connect network... let it sync.

If I trash the note on the mac app or the iOS app, it's trashed on those apps but not on the electron app. If I trash it on the electron app, it dos not get trashed on other apps. No javascript errors 😞

**Comment by roundhill** [comment]
I was able to reproduce. You cool with filing a separate issue for that? I don't think it's related to the Simperium change.

**Comment by rodrigoi** [comment]
I think the issues are related because it only happens to me with notes created offline. But it may require further investigation, therefore, I'm cool with having a separate issue.

tumblr_inline_nltjbxhp7y1rbra2d

:shipit: :shipit: :shipit:

**Comment by roundhill** [comment]
@rodrigoi OS X should be fixed now. Care to give it another look?

**Pull request merged**
