### PR TITLE
Add a title bar space for Mac Electron

### LINKED ISSUE #2886: [macOS] Window top corners look both rounded and sharp under dark theme
### Expected
Window corners should either be rounded or square. Also, all corners (top/bottom) should have the same shape. 

### Observed
Desktop app top corners under dark theme are shown as primarily rounded, but also with a sharp outline that gives a feeling of a bounding box:

Screenshot 2021-05-04 at 12 11 27

### Reproduced
1. Activate `Dark` theme
2. Take a look on the top corners of the app window

### Where did you see the bug
- System Model: MBP 16"
- OS: Big Sur 11.2.3
- Simplenote app version: 2.11.0-beta1 desktop

### PR DESCRIPTION
**Pull request by sandymcfadden**
### Fix

Previously we had been adding specific styles to different components for only Mac Electron app to prevent things from overlapping the window buttons.

This removes those and instead enables the default title bar.

To have this work well I also updated the Electron dependency to fix some issues with the rounded corners. With that also updated Electron Builder.

Resolves #2886

The Electron update introduced two issues one where logging out wouldn't refresh to the login screen. The other the Linux build wouldn't render properly.
Both of those have fixes here as well.

<details>
<summary>Before</summary>
Screen Shot 2021-04-23 at 9 06 44 PM
Screen Shot 2021-04-23 at 9 06 05 PM
</details>
<details>
<summary>After</summary>
Screen Shot 2021-05-03 at 9 16 37 AM
Screen Shot 2021-05-03 at 9 16 08 AM
</details>

### Test

1. Run Mac Electron app.
2. Ensure bar appears at the top with the app below it as usual.
3. Check other Electron builds to ensure they work as expected.

### Release

- Added title bar area to the Mac Electron app
- Updated Electron and Electron Builder dependencies

### CODE REVIEW

**Review by SylvesterWilmott — APPROVED** [review]
Nice improvement! Thanks @sandymcfadden

**Review by codebykat — CHANGES_REQUESTED** [review]
This is looking weird to me and not like the screenshots... the buttons aren't vertically aligned:

Screen Shot 2021-04-30 at 2 43 06 PM

Could it be a Catalina / Big Sur thing? (I'm still on Catalina.) I did do a full `npm install`.

Other apps don't have this issue:

Screen Shot 2021-04-30 at 2 43 26 PM

Screen Shot 2021-04-30 at 2 43 14 PM

Screen Shot 2021-04-30 at 2 43 51 PM

Edit: Here's the "before" for comparison:

Screen Shot 2021-04-30 at 3 02 51 PM

**Comment by sandymcfadden** [comment]
Ah thank you @codebykat. I bet you're right, I only tested on Big Sur. I think I have a computer that hasn't been upgraded yet so I'll test it out there and figure things out.

**Comment by sandymcfadden** [comment]
I've updated this now @codebykat. I realized that there is an option that we can enable the default title bar for Mac to take care of the issue I was trying to fix. I've done that now and it seems to be working well on Big Sur and Catalina. The major difference between how I was doing it and how it is now is that it shows the app title in the title bar now.

**Review by belcherj — CHANGES_REQUESTED** [review]
Could you split the electron upgrade from the title bar changes?

**Comment by sandymcfadden** [comment]
Closing this off and opening two others splitting out the main tasks into them.

**Pull request closed without merging**
