### PR TITLE
Navigation Bar: complete refactor (ES6, Redux, CSS)

### PR DESCRIPTION
**Pull request by Copons**
### ⚠️ VERY WIP ⚠️

Create new `NavigationBar`, `TagList`, `EditableList` components, all almost
completely independent from the root `App` component (except for the
buckets).

### CODE REVIEW

**Comment by dmsnell** [comment]
@copons I like what you are doing with the props. Do you think it would be possible to do _just_ the prop/action moves in another PR that logically precedes this one? I think that would be stellar and could be done in a PR which doesn't introduce any functional changes to the app.

**Comment by Copons** [comment]
@dmsnell I'm not sure I got what you mean with functional changes. 
The only differences right now are the ES6ification of the functions (and the moving of the components into their own folders), but other than that it's exactly the same as before.

**Comment by dmsnell** [comment]
@copons what's the status on this PR? does it need updating, does it need splitting, does it need abandoning?

**Comment by rodrigoi** [comment]
Closing this as stale. @Copons, feel free to reopen this any time.

**Pull request closed without merging**
