### PR TITLE
Add an 'X' button to clear a search query

### PR DESCRIPTION
**Pull request by roundhill**
Added an ‘x’ button to the search field that shows if there’s any characters in the search query.

screen shot 2017-01-05 at 11 04 18 am

It even fades in and out 🌈

**To test**
* Type in the search field, you should see the 'x' appear.
* Click the 'x' and the search query should clear out and the notes list resets.
* Try other search box things like hitting escape to verify it works properly.

### CODE REVIEW

**Comment by dmsnell** [comment]
@roundhill I'm getting the following error trying to `npm install`

```
Error: Cannot find module 'internal/fs'
```

did you see this? if you `rm -rf node_modules` and then `npm install` do you get it?

**Comment by roundhill** [comment]
> search input is fatter

Oh, I had to move the padding around to make space for the `X`. Should be easy to fix

**Comment by dmsnell** [comment]
Yes it's fatter and also @roundhill I noticed a bold white outline around the search box that isn't there in **master**

**Comment by roundhill** [comment]
Here's some tweaks to the height. I think it's actually a pixel or two larger than the how it was, though.

screen shot 2017-01-05 at 1 18 54 pm

**Comment by dmsnell** [comment]
**master**
screen shot 2017-01-05 at 3 00 06 pm

**this branch**
screen shot 2017-01-05 at 2 55 05 pm

@roundhill this is running inside of Electron

**Comment by roundhill** [comment]
> @roundhill this is running inside of Electron

Ah, forgot about the dark theme! Fixed in dd7fa98

**Comment by Copons** [comment]
Code-wise LGTM 👍

**Comment by dmsnell** [comment]
@roundhill the design changes are so subtle here and with @drw158 out for the week I would think this  is ready to go

**Comment by roundhill** [comment]
OK, I'll merge. I sort of received a thumbs up on the design over slack last week.

**Pull request merged**
