### PR TITLE
Fix: Icon and pinner styles in navigation and notes list

### PR DESCRIPTION
**Pull request by codebykat**
### Fix

This fixes some incorrect icon colors and makes some progress in untangling these component styles generally. Follow-up to #2580.

Designs:
* https://app.zeplin.io/project/5d795a3d8ed5261aa146e057/screen/5fbbc5e81bc37159baf42a47
* https://app.zeplin.io/project/5d795a3d8ed5261aa146e057/screen/5fbbc5347608905ee4ae2dd3
* https://app.zeplin.io/project/5d795a3d8ed5261aa146e057/screen/5fbbc5d768735855a07651d9
* https://app.zeplin.io/project/5d795a3d8ed5261aa146e057/screen/5fbbc5944b88d656997f593a

### Test

1. In both light and dark themes:
1. Verify that the navigation list has the right icon colors that don't change when hovered over
2. Verify the notes list has the right backgrounds and hovers for selected / pinned / hovered notes
3. Verify the pin icon in the notes list:
3a. Only is shown on pinned notes (unless hovered)
3b. Is visible when a pinned note is selected
3c. Is not shown when a non-pinned note is selected (unless hovered)
3d. Changes color in all of the above states, when hovered over, to indicate it can be clicked
4. Make sure published icon is legible for all note states (selected, hover)
5. Make sure syncing and offline/unsynced icon is legible for all note states

### Screenshots

Screen Shot 2021-01-23 at 9 42 13 PM

Screen Shot 2021-01-23 at 9 42 10 PM

Screen Shot 2021-01-23 at 9 42 47 PM
  
Screen Shot 2021-01-23 at 9 42 32 PM

Screen Shot 2021-01-23 at 9 42 52 PM

### Release

Fixed icon and pinner styles in the navigation and notes list

### CODE REVIEW

**Review by sandymcfadden — COMMENTED** [review]
Things are looking really good. There are a few items I ran across while going through the testing. I haven't dug into the code yet to where the differences are.

The hover color for notes list on dark mode doesn't seem to match the colors. This is the same for pinned note background color.
This brings up a bigger conversation around the new color pallet for dark mode, especially around elevation.
https://app.zeplin.io/project/5d795a3d8ed5261aa146e057/screen/5db2c14aba30fd54e7149b20
Are we going to go with existing colors for now and then implement the new colors separately at another time?

- Light mode: Default pinned icon color is #646970 should be #3361cc.
- Light mode: When a note is selected and pinned, if you hover over the pin it doesn't change color.
- Dark mode: Default pinned icon color is #646970 should be #618df2.

**Comment by codebykat** [comment]
Oookay I think I got the default colors fixed. Good catch @sandymcfadden I had flipped the blues and grays.

It's not 100% clear to me from the designs what we should do with the pinner hovers (if they should still have them) when the notes are also hovered. For now I set the hovers to the default color, except for the selected note, which uses default color as the hover since the selected note shouldn't have a hover state. (Clear as mud? Yeah, me too.)

I'd like to merge this so we can deploy to develop and @SylvesterWilmott can try them out and we can iterate.

**Comment by codebykat** [comment]
The elevation question is a totally different one I believe.

**Comment by pachlava** [comment]
[testing] Checked that (in both themes):
- Sidebar icons now have correct highlighting
- Pin icon for pinned note changes colour on hover
- pin / published / unsynced icons look legible

Win 10 | SN desktop 2.6.0-beta1

**Pull request merged**
