### PR TITLE
Add Spellchk Supprt

### PR DESCRIPTION
**Pull request by roundhill**
It's a real shame that the app doesn't support spellcheck (#312). I've got a good start to getting it working by utilizing Electron's `spellCheckProvider`. It now shows spelling errors in the editor:

screen shot 2018-04-24 at 1 35 04 pm

~But, you can't take any action on it. We need to get the spelling suggestions and pass them into our `context-menu` component and make them actionable. @dmsnell if you're ever twiddling your thumbs maybe you could take this on? Next 🍺 on me.~
Did this ^

### CODE REVIEW

**Comment by dmsnell** [comment]
Tough one @roundhill - this will come with much acclaim but not having suggestions and corrections is a big deal I think. I'm not sure how this will tie in to the editor work we've looked at (#692)

Maybe over the weekend I can try and put some time on this.

**Comment by roundhill** [comment]
@dmsnell I got it working 🎉

screen shot 2018-05-15 at 2 12 21 pm

Turns out a `context-menu` in electron provides a misspelled work if there is one beneath where it was called. 

I am having a problem with the `node-spellchecker` lib though, it is a native module and I'm not able to figure out how to package the app while building the .node file for the windows or linux platforms from macOS. We might have to build and package from windows and linux itself?

**Comment by roundhill** [comment]
@dmsnell Ready for a review here as well. I was 🤔, should we also add a menu option to disable spellcheck? I'd imagine some users would not want it.

**Comment by roundhill** [comment]
@adlk mentioned that this library may be better to use: https://github.com/electron-userland/electron-spellchecker

We could also just use that lib for copy/paste/undo commands in the right-click menu, but we'd want to ensure that you can still copy the markdown preview content via right-click as well.

**Comment by roundhill** [comment]
Closing in favor of #821

**Pull request closed without merging**
