### PR TITLE
Allow unselecting tags by keyboard

### PR DESCRIPTION
**Pull request by qualitymanifest**
### Fix
Closes https://github.com/Automattic/simplenote-electron/issues/1852
If a tag is selected and the right arrow key is pressed, the tag is unselected and the focus is moved back into the tag field.

### Test
See the issue for details to reproduce, but use right arrow to unselect

### Review
Only one developer is required to review these changes, but anyone can perform the review.

### Release
Release notes updated in bde11cf

### CODE REVIEW

**Comment by qualitymanifest** [comment]
Just realized I forgot about the tab key! I'll add that in in a second. I figure I'll leave the right arrow control in as well, that's the way that I would naturally think to exit the tag chip.

**Comment by qualitymanifest** [comment]
Good point, I didn't see the key handlers in `tag-input`

It looks like `tag-input`'s `onChange` does called for regular keypresses though, inside `onInput` (a few times - might be worth looking into?), and `this.state.tagInput` does get updated. Here's a screenshot of two keypresses (red line separating them) with a bunch of console.logs peppered in:
snote

I think the reason why `tag-input` doesn't intercept keyboard events when a tag is selected is because when a tag is "selected", the focus is actually on `hidden-tag` which is a child of `tag-field` and unrelated to `tag-input`

**Comment by qualitymanifest** [comment]
Actually now that I re-read your comment I'm confused regarding the `interceptKeys` comment, mainly because `tag-field` and `tag-input` both have an `interceptKeys` method so I'm not sure which one you're referring to.

`tag-input`'s tab and and right-arrow handlers are for completing a suggestion, not for handling keyboard events when a tag-chip (really, `hidden-tag`) is "selected".

`tag-field`'s only current key handler, backspace, is for deleting a tag-chip when it is "selected" - so I think it makes sense to also put the other tag-chip key handlers here.

I could definitely be missing something though!

**Comment by dmsnell** [comment]
@qualitymanifest what I was seeing at a cursory glance was that we only seem to be sending the updated tag text from `tag-input` to `tag-field` when we select a tag or accept the tag suggestion. because of this, when the `tag-field` intercepts the key presses it's making an assertion about the current `tag-input` text that's "out of date."

in other words, both components should agree that the input text is `compu` when we are typing `computer` but haven't yet finished typing. I believe that the parent component only sees `` until at the end of the typing it gets told "choose `computer`"

**Comment by qualitymanifest** [comment]
@dmsnell From my understanding, `tag-field`'s state is getting updated on each keypress. `tag-input`'s `inputObserver` is triggered on keypress and kicks off `onInputMutation` -> `onInput` -> `onChange` -> `tag-field`'s `storeTagInput` where it is updated

That being said - it seems unrelated to the issue of being able to key out of a tag-chip. `tag-field`'s current `interceptKeys` handler is only for selecting and deleting a tag chip, and there is no key handler to unselect that tag-chip

**Comment by qualitymanifest** [comment]
Made the changes, reads a lot better with the constants @dmsnell

**Pull request merged**
