### PR TITLE
Chore: Update monaco editor (again), to 0.22.0

### PR DESCRIPTION
**Pull request by codebykat**
### Fix

This was just released and includes the fix for the missing action triggers from 0.21.x (see #2604) AND the fix for the double emoji insertion in Firefox (#2327) !!!

I had to explicitly import `Range` to avoid an error, this needs VERY THOROUGH testing in case anything else has been subtly broken. There are literally thousands of vscode commits in the past couple of versions.

### Release

Updated Monaco editor to 0.22.0

### CODE REVIEW

**Comment by sandymcfadden** [comment]
So far I've gone through and testing this in the web on Mac, Windows, and Linux. I also tested in the Mac Electron build.

The things I tested were:
- Search highlighting
- Note linking
- External linking
- Lists
- Task items
- Keyboard shortcuts
- Editor keyboard commands

All seem to be working well save a few edge case keyboard shortcuts like
- Ctrl + Shift + U Doesn't work on Linux
- Ctrl + Shift + P Doesn't work on Linux Firefox

Hoping to test the Linux and Windows builds as well but so far having issues getting the Linux build to complete in CircleCI so I can't download the artifacts.

**Comment by sandymcfadden** [comment]
It also looks like this resolves #2579.

**Comment by codebykat** [comment]
I merged in the compression format change from #2620 and this seems to build on Linux now! Props @sandymcfadden for that fix

**Comment by codebykat** [comment]
I downloaded the .deb file and got this installed on Debian (Parallels), smoke-tested, it seems to work fine!

**Review by sandymcfadden — APPROVED** [review]
Tested this out again on Linux and Windows builds and everything looks good.
Thanks for getting these updates made!

**Pull request merged**
